version: '3.1'

services:
  db:
    container_name: kazokku-db
    image: postgres:latest
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "${DB_PORT}:5432"
  app:
    container_name: kazokku-app
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      - DB_HOST=db
    ports:
      - "${APP_PORT}:${APP_PORT}"
    depends_on:
      - db
    volumes:
      - "./app_data:${SAVE_DIR}"
    restart: always
