version: '3.1'

services:
  db:
    container_name: kazokku-db
    image: postgres:latest
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "${DB_PORT}:5432"
    healthcheck:
      test: "pg_isready -U ${DB_USERNAME} -d ${DB_NAME} -h localhost -p 5432"
      interval: 5s
      timeout: 60s
      retries: 3
      start_period: 5s
  app:
    container_name: kazokku-app
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      - DB_HOST=db
      - DB_PORT=5432
    ports:
      - "${APP_PORT}:${APP_PORT}"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - "./app_data:${SAVE_DIR}"
    restart: always
